#!/usr/bin/env bash

SCRIPT_NAME="./script"
HELP_USAGE="For help, run: ${SCRIPT_NAME} --help"
NAME_USAGE="<NAME> cannot be empty"
PREFIX_USAGE="<PREFIX> cannot be empty"
USAGE="\
Usage:
  ${SCRIPT_NAME} [OPTIONS] -- <NAME>

${NAME_USAGE}

OPTIONS:
  -h, --help              Show this help
  -u, --uppercase         Uppercase the <NAME>
  -p, --prefix <PREFIX>   Change the greeting prefix"

uppercase_option="false"
prefix_option="Hello"
name_arg=""
backwards_name=""
today=""
output=""

handle_help() {
  echo -e "${USAGE}"
  exit 0
}

die() {
  echo "${HELP_USAGE}"
  exit 1
}

handle_unknown_option() {
  local option="${1}"
  echo "Unknown option: ${option}"
  die
}

handle_empty_arg() {
  local arg_usage="${1}"
  echo "${arg_usage}"
  die
}

uppercase_string() {
  local str="${1}"
  echo "$(echo "${str}" | tr '[:lower:]' '[:upper:]')"
}

reverse_string() {
  local str="${1}"
  echo "$(echo "${str}" | rev)"
}

get_today() {
  echo "$(date -u '+%F')"
}

if [[ ${#} == 0 ]]; then
  handle_empty_arg "${NAME_USAGE}"
fi

while [[ ${#} -gt 0 ]]; do
  case ${1} in
    -h | --help)
      handle_help
      ;;
    -u | --uppercase)
      uppercase_option="true"
      shift
      ;;
    -p | --prefix)
      shift
      prefix_option="${1}"
      if [[ -z "${prefix_option}" ]]; then 
        handle_empty_arg "${PREFIX_USAGE}"
      fi 
      shift
      ;;
    --)
      shift
      break
      ;;
    *)
      handle_unknown_option "${1}"
      ;;
  esac
done

name_arg=${1}

if [[ -p /dev/stdin ]]; then
  name_arg="$(cat -)"
fi

if [[ -z "${name_arg}" ]]; then 
  handle_empty_arg "${NAME_USAGE}"
fi 

if [[ ${uppercase_option} == "true" ]]; then
  name_arg="$(uppercase_string "${name_arg}")"
fi

backwards_name="$(reverse_string "${name_arg}")"
today="$(get_today)"

output="\
${prefix_option}, ${name_arg}
Your name backwards is ${backwards_name}
Today is ${today}"

echo "${output}"

echo "Completed in ${SECONDS} s"
